server:
  port: 11001

spring:
  application:
    name: pos-order
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: Saw0rk_2o22

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
