server:
  port: 8080

spring:
  application:
    name: pos-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pos-products
          uri: lb://pos-products
          predicates:
            - Path=/api/products/**

        - id: pos-carts
          uri: lb://pos-carts
          predicates:
            - Path=/api/carts/**

        - id: pos-orders
          uri: lb://pos-orders
          predicates:
            - Path=/api/orders/**

        - id: pos-delivery
          uri: lb://pos-delivery
          predicates:
            - Path=/api/delivery/**

        - id: pos-frontend
          uri: http://localhost:3000
          predicates:
            - Path=/**

eureka:
  instance:
    instance-id: pos-gateway8080
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
