server:
  port: 12001

spring:
  application:
    name: pos-delivery
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: Saw0rk_2o22

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
