server:
  port: 12001

spring:
  application:
    name: pos-delivery

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
