openapi: "3.0.0"

info:
  version: 1.0.0
  title: Products
  license:
    name: MIT

paths:
  /products:
    get:
      summary: List all products
      operationId: listProducts
      tags:
        - products
      responses:
        200:
          description: A paged array of products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /products/{productId}:
    get:
      summary: Info for a specific product
      operationId: showProductById
      tags:
        - product
      parameters:
        - name: productId
          in: path
          required: true
          description: The id of the product to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /products/pager:
    get:
      summary: Get a page of products
      operationId: getProductsInPage
      tags:
        - products
      parameters:
        - name: page
          in: query
          required: true
          description: page number
          schema:
            type: integer
        - name: pageSize
          in: query
          required: true
          description: how many products per page
          schema:
            type: integer
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageResult"

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: double
        image:
          type: string

    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"

    PageResult:
      type: object
      properties:
        total:
          type: integer
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
